### ISSUE TITLE
boost_mpi

### ISSUE THREAD

**Issue by qingqing01** [Evolving-AI-Lab/fooling#1]
The "sferes" needs boost_mpi. When I installed boost_1.57.0, there is mpi "include file", but there is no boost_mpi lib. I serarch the internet.
"
adding the following line to your user-config.jam file
using mpi ;
then 
bjam --with-mpi
"
But I cann't find user-config.jam file in the boost path. I have installed MVAPICH2 2.0。

**Comment by anguyen8** [comment]
@Dcocoa To make sure, can you print out the output of your 
`./waf --configure` in Sferes folder?

Does it match the example output in the Installation_Guide.pdf?

**Comment by qingqing01** [comment]
The following is the output of the <addr> ./waf --configure. The library boost_mpi can not be found.

Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Checking for g++                         : ok  
boost headers                            : Version 1_57 
library boost_serialization              : ok 
library boost_filesystem                 : ok 
library boost_system                     : ok 
library boost_unit_test_framework        : ok 
library boost_program_options            : ok 
library boost_graph                      : ok 
library boost_mpi                        : not found 
library boost_python                     : ok 
library boost_thread                     : ok 
Checking for header tbb/parallel_for.h   : not found 
Checking for header tbb/parallel_for.h   : not found 
Checking for header mpi.h                : not found 
Checking for SDL (optional)              : not found 
Checking for header Eigen/Core           : ok /home/dangqingqing/src/sferes/include 
Check for program ode-config             : not found 
Checking for ODE (optional)              : not found 
Checking for GSL (optional)              : not found 
--- configuration ---
compiler:
- CXX: gcc
  boost version: 1_57
  mpi: False

**Comment by qingqing01** [comment]
I have installed boost_mpi library. In ther version of boost 1.57.0, need to add "using mpi" in the project-config.jam.  O(∩_∩)O~

**Comment by qingqing01** [comment]
@anguyen8 Thanks a lot :)

**Comment by anguyen8** [comment]
@Dcocoa : Great! I was about to say that the configure output shows Sferes couldn't find your Boost::MPI .

Btw, please use one Boost version only and use it to build both Caffe and Sferes. Otherwise, you might run into conflicts later (as both frameworks use Boost).
