### ISSUE TITLE
ERROR occurs when type command: make all

### ISSUE THREAD

**Issue by urumican** [Evolving-AI-Lab/fooling#10]
Hi, I have a problem when installing caffe. 

When I use command: 

`make all`

I get:

```
find: ‘examples’: No such file or directory
find: ‘examples’: No such file or directory
protoc --proto_path=src --cpp_out=.build_release/src src/caffe/proto/caffe.proto
make: protoc: Command not found
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 127
```

Is there any other dependencies that need to be installed? I don't exactly know what "example" referring to. And I am not sure what protoc is.

**Comment by anguyen8** [comment]
@urumican : The `examples` error should not prevent you from compiling this (you could ignore the "No such file" message). 

I think you're hitting a different issue, like https://github.com/BVLC/caffe/issues/617

**Comment by urumican** [comment]
Thank you very much! I tried them and it react differently. Now I get the result

```
.build_release/src/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
.build_release/src/caffe/proto/caffe.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
.build_release/src/caffe/proto/caffe.pb.cc: In function ‘void caffe::protobuf_AssignDesc_caffe_2fproto_2fcaffe_2eproto()’:
.build_release/src/caffe/proto/caffe.pb.cc:144:24: error: no matching function for call to ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, caffe::BlobProto*&, const int [6], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(BlobProto));

```

Do you know which version of protoc you were uring?

**Comment by anguyen8** [comment]
@urumican : Sorry, I don't remember exactly (it was 1.5 years ago), but protobuf 2.5.x or 2.6.x .

If you just want to reproduce the Evolutionary algorithm fooling results on ImageNet.
You could also do that using this (more recent) repo: https://github.com/Evolving-AI-Lab/innovation-engine

**Comment by urumican** [comment]
Thank you very much!
