### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by johnmenick** [Evolving-AI-Lab/fooling#11]
Do you think it would be possible to publish a Docker image for this experiment?

**Comment by anguyen8** [comment]
@johnmenick I personally don't use Docker and probably won't have time to create it. But everyone is welcome to. :)

**Comment by johnmenick** [comment]
Since one needs to compile custom versions of Caffe and Sferes2, as well as run old versions of Cuda, etc., it's an extremely high barrier of entry to get these experiments to run, even for someone with decent sysadmin skills. A docker image would eliminate the need to for "everyone" to go through dependency hell on outdated dependencies and unknown platform configs.
