### ISSUE TITLE
Error in step "caffe make runtest" and "run mnist experiment"

### ISSUE THREAD

**Issue by RanTaimu** [Evolving-AI-Lab/fooling#14]
system: Ubuntu 14.04 LTS

I use "dl_map_elites_images_mnist_direct_encoding.cpp" to do the test. The error seems to be caused by "caffe::OpenCVImageToDatum()" and "ReadImageToDatum()" :

Run "caffe make runtest -j16":
> [ RUN      ] FormatTest/0.TestOpenCVImageToDatum
F0307 14:24:24.129835 29969 format.cpp:17] Check failed: image.data Image data must not be NULL
*** Check failure stack trace: ***
    @     0x2af695d6fdaa  (unknown)
    @     0x2af695d6fce4  (unknown)
    @     0x2af695d6f6e6  (unknown)
    @     0x2af695d72687  (unknown)
    @           0x5b2316  caffe::OpenCVImageToDatum()
    @           0x429f87  caffe::FormatTest_TestOpenCVImageToDatum_Test<>::TestBody()
    @           0x571083  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x567c67  testing::Test::Run()
    @           0x567d0e  testing::TestInfo::Run()
    @           0x567e15  testing::TestCase::Run()
    @           0x56b158  testing::internal::UnitTestImpl::RunAllTests()
    @           0x56b3e7  testing::UnitTest::Run()
    @           0x414030  main
    @     0x2af698338f45  (unknown)
    @           0x41a787  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

Run the executable file:
> [ images ] $ ./images 
[A]: 
sferes2 version: (const char*)"0.1"
seed: 1488897135
F0307 14:22:50.208117 29366 image_data_layer.cpp:208] Check failed: ReadImageToDatum(lines_[lines_id_].first, lines_[lines_id_].second, new_height, new_width, images_in_color, &datum) 
*** Check failure stack trace: ***
    @     0x7f5e5f069daa  (unknown)
    @     0x7f5e5f069ce4  (unknown)
    @     0x7f5e5f0696e6  (unknown)
    @     0x7f5e5f06c687  (unknown)
    @     0x7f5e5fa0f28b  caffe::ImageDataLayer<>::SetUp()
    @     0x7f5e5f9ecc68  caffe::Net<>::Init()
    @     0x7f5e5f9edcc5  caffe::Net<>::Net()
    @           0x42846b  sferes::fit::FitMapDeepLearning<>::_setProbabilityList()
    @           0x428c37  sferes::eval::Eval<>::eval<>()
    @           0x42e48d  sferes::ea::MapElite<>::random_pop()
    @           0x42e718  sferes::ea::Ea<>::run()
    @           0x41a037  main
    @     0x7f5e5d3d3f45  (unknown)
    @           0x4189f9  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by anguyen8** [comment]
@RanTaimu : seems like some compatibility issue between Caffe vs OpenCV.
