### ISSUE TITLE
no attribute 'backward_from_layer'

### ISSUE THREAD

**Issue by lixyresearch** [Evolving-AI-Lab/fooling#2]
when i run find_fooling_image.py
This came: AttributeError: 'Classifier' object has no attribute 'backward_from_layer'.
How can i fix it?

**Comment by anguyen8** [comment]
@lxycnu : If you run the gradient ascent code, please install the lastest Caffe which supports that attribute  `backward_from_layer`. The Caffe version included in this repo is only for the evolutionary code.

**Comment by lixyresearch** [comment]
I have tried the current version, but it also does not support the attribute of ' backward_from_layer. Maybe i can use 'backward' instead of '(Net.backward = _Net_backward) backward_from_layer '.

**Comment by lixyresearch** [comment]
backout = net.backward_from_layer(push_layer, diffs)
 # backout=net.backward(diffs,push_layer)
......
I change it like this, but it still has some problem. Can you give me some suggestion?

**Comment by anguyen8** [comment]
@yosinski : Can you share which Caffe version you used to have working with find_fooling_image.py?

**Comment by yosinski** [comment]
@anguyen8 @lxycnu Oops, I see that I forgot to push that modification to Caffe. I'll push it ASAP.

**Comment by yosinski** [comment]
@lxycnu Try again using these [updated instructions](https://github.com/Evolving-AI-Lab/fooling/tree/ascent/caffe/ascent) and the ascent branch. I just tried and it works for me.
