### ISSUE TITLE
Unable to generate MNIST example

### ISSUE THREAD

**Issue by antinucleon** [Evolving-AI-Lab/fooling#5]
After I change `dl_images.hpp`, `dl_map_elites_images_mnist.cpp` and generated MNIST images, I compiled the program. I get segfault. But when I run caffe independently, it works well. I opened GLOG, the output is like

```
I0525 23:13:19.182551 27365 net.cpp:207] Collecting Learning Rate and Weight Decay.
I0525 23:13:19.182559 27365 net.cpp:130] Network initialization done.
I0525 23:13:19.182565 27365 net.cpp:131] Memory required for data: 0
Segmentation fault (core dumped)
```

**Comment by anguyen8** [comment]
@antinucleon : Were you ever able to generate MNIST images before this segfault?

If you can provide gdb stacktrace , I can help with debugging.

**Comment by antinucleon** [comment]
The tracking info suggest it is crashed at OpenBlas, I will post full info soon. It is strang that I can run Caffe in CPU mode correctly.

**Comment by anguyen8** [comment]
@antinucleon : Ok, make sure that you don't have multiple conflicting versions of Caffe installed on your system.
